# Optimization Algorithms for Minimizing Loss Functions

Optimization algorithms are essential for minimizing loss functions in machine learning models. In this notebook, we will explore the following optimization techniques:

1. **Gradient Descent (GD)**
2. **Batch Gradient Descent (BGD)**
3. **Stochastic Gradient Descent (SGD)**
4. **Mini-batch Gradient Descent (MBGD)**
5. **Simulated Annealing (SA)**
6. **Evolutionary Computing (EC)**

In [70]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd
import random

In [71]:
X,y = load_diabetes(return_X_y=True)

In [72]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [73]:
from sklearn.linear_model import LinearRegression

In [74]:
lr = LinearRegression()
lr.fit(X,y)
lr.intercept_,lr.coef_

(152.13348416289597,
 array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
        -792.17563855,  476.73902101,  101.04326794,  177.06323767,
         751.27369956,   67.62669218]))

## 1. Gradient Descent (GD)

### Overview
Gradient Descent is a first-order iterative optimization algorithm used to minimize a loss function by moving in the direction of the steepest descent, as defined by the negative of the gradient.

### Algorithm Steps
1. Initialize the parameters (e.g., weights \( \theta \)) randomly.
2. Compute the gradient of the loss function \( J(\theta) \) with respect to \( \theta \):
   $$
   \nabla J(\theta) = \frac{\partial J(\theta)}{\partial \theta}
   $$
3. Update the parameters:
   $$
   \theta = \theta - \alpha \nabla J(\theta)
   $$
   where \( \alpha \) is the learning rate.
4. Repeat steps 2–3 until convergence.

### Advantages
- Simple and easy to implement.
- Guaranteed to converge to a local minimum for convex functions.

### Disadvantages
- Computationally expensive for large datasets.
- May get stuck in local minima for non-convex functions.

---

## 2. Batch Gradient Descent (BGD)

### Overview
Batch Gradient Descent is a variant of Gradient Descent where the gradient is computed using the **entire training dataset** in each iteration.

### Algorithm Steps
1. Initialize the parameters \( \theta \).
2. Compute the gradient of the loss function \( J(\theta) \) using all training examples:
   $$
   \nabla J(\theta) = \frac{1}{N} \sum_{i=1}^N \nabla J_i(\theta)
   $$
   where \( N \) is the number of training examples.
3. Update the parameters:
   $$
   \theta = \theta - \alpha \nabla J(\theta)
   $$
4. Repeat until convergence.

### Advantages
- Stable convergence.
- Computes the gradient accurately.

### Disadvantages
- Computationally expensive for large datasets.
- Requires memory to store the entire dataset.

---


In [ ]:
def Gradient_Descent_Regressor(X,y,epochs,lr):
    intercept_ = 1 #intialize random intercept
    w = np.ones(X.shape[1]) #intialize random Weights

    for i in range(epochs):# Run for no of iterations

        y_hat = np.dot(X,w)+intercept_ 
        intercept_slope = -2*np.mean(y-y_hat) # calculate slope of coefficients
        intercept_ = intercept_ - (lr*intercept_slope)  # gradient descent algorithm

        coef_der = -2 * np.dot((y-y_hat),X) # calculate slope of coefficients
        w = w - (lr*coef_der) # gradient descent algorithm
    return intercept_,w



In [ ]:
Gradient_Descent_Regressor(X,y,1000,.2) # Display intercept and coefficient w1,w2,.....wn

(152.133484162896,
 array([  -9.89634498, -239.68827656,  520.13289095,  324.27252567,
        -767.47869527,  457.14240219,   89.99761315,  173.91090519,
         742.07148   ,   67.71752944]))

## 3. Stochastic Gradient Descent (SGD)

### Overview
Stochastic Gradient Descent is a variant of Gradient Descent where the gradient is computed using **one training example** at a time.

### Algorithm Steps
1. Initialize the parameters \( \theta \).
2. Shuffle the training dataset.
3. For each training example \( i \):
   - Compute the gradient of the loss function \( J_i(\theta) \):
     $$
     \nabla J_i(\theta)
     $$
   - Update the parameters:
     $$
     \theta = \theta - \alpha \nabla J_i(\theta)
     $$
4. Repeat until convergence.

### Advantages
- Faster computation per iteration.
- Can escape local minima due to noise in gradient updates.

### Disadvantages
- High variance in updates, leading to unstable convergence.
- May require careful tuning of the learning rate.

---


In [ ]:
def Stochastic_Gradient_Descent_Regressor(X,y,epochs,lr):
    intercept_ = 1
    w = np.ones(X.shape[1])

    for i in range(epochs): #Run for no of iterations
        for j in range(X.shape[0]):
            idx = np.random.randint(0,X.shape[0]) # Select a random row number for algorithm
            y_hat = np.dot(X[idx],w)+intercept_ # find y_hat 
            intercept_slope = -2*np.mean(y[idx]-y_hat) # Calculate slope of intersept
            intercept_ = intercept_ - (lr*intercept_slope) # Calculate new intercept using gradient descent

            coef_der = -2 * np.dot((y[idx]-y_hat),X[idx]) # Calculate slope of weights
            w = w - (lr*coef_der) # Calculate new weights using gradient descent
    return intercept_,w

In [ ]:
Stochastic_Gradient_Descent_Regressor(X,y,3500,.001) # Display intercept and coefficient w1,w2,.....wn

(150.3000881610654,
 array([  -6.30510417, -238.55800357,  528.57621174,  320.66580846,
         -76.19879489, -104.999583  , -202.85631572,  115.66270026,
         472.60481143,   72.81232669]))

## 4. Mini-batch Gradient Descent (MBGD)

### Overview
Mini-batch Gradient Descent is a compromise between Batch Gradient Descent and Stochastic Gradient Descent. It computes the gradient using a **small batch of training examples** in each iteration.

### Algorithm Steps
1. Initialize the parameters \( \theta \).
2. Shuffle the training dataset.
3. Split the dataset into mini-batches of size \( b \).
4. For each mini-batch:
   - Compute the gradient of the loss function \( J(\theta) \):
     $$
     \nabla J(\theta) = \frac{1}{b} \sum_{i=1}^b \nabla J_i(\theta)
     $$
   - Update the parameters:
     $$
     \theta = \theta - \alpha \nabla J(\theta)
     $$
5. Repeat until convergence.

### Advantages
- Balances computational efficiency and convergence stability.
- Suitable for large datasets.

### Disadvantages
- Requires tuning of the batch size \( b \).

---


In [ ]:
def Mini_batch_Gradient_Descent(X,y,epochs,lr,batch_size):
    intercept_ = 1
    w = np.ones(X.shape[1])

    for i in range(epochs):# Run for no of iterations
            for j in range(int(X.shape[0]/batch_size)): # Run for no of batches
                idx = random.sample(range(X.shape[0]),batch_size) # select random batch for mini batch gradient descent
                y_hat = np.dot(X[idx],w)+intercept_
                intercept_slope = -2*np.mean(y[idx]-y_hat) # Calculate slope of intersept
                intercept_ = intercept_ - (lr*intercept_slope) # Calculate new intercept using gradient descent

                coef_der = -2 * np.dot((y[idx]-y_hat),X[idx]) # Calculate slope of weights
                w = w - (lr*coef_der)  # Calculate new weights using gradient descent
    return intercept_,w

In [ ]:
Mini_batch_Gradient_Descent(X,y,3500,.001,10) # Display intercept and coefficient w1,w2,.....wn

(152.31910605459362,
 array([  -1.9406203 , -236.47053329,  526.60222316,  322.06406415,
         -76.09484011, -105.60738531, -204.05457614,  113.92118568,
         475.13670733,   75.4354011 ]))